# -*- coding: utf-8 -*-
"""TwitterSentimentAnalysis_NLP Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ou8smJfEe6b2o8ZsdkIbZsGNzrNtxj3
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("jp797498e/twitter-entity-sentiment-analysis")

print("Path to dataset files:", path)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import re

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.pipeline import Pipeline
import joblib
from sklearn.metrics import accuracy_score, classification_report

train_df = pd.read_csv(
    "/kaggle/input/twitter-entity-sentiment-analysis/twitter_training.csv",
    header=None,
    names=["ID", "Topic", "Sentiment", "Text"]
)

valid_df = pd.read_csv(
    "/kaggle/input/twitter-entity-sentiment-analysis/twitter_validation.csv",
    header=None,
    names=["ID", "Topic", "Sentiment", "Text"]
)

train_df.info()

train_df[["Topic", "Sentiment", "Text"]].describe()

train_df.Topic.value_counts()

train_df.Sentiment.value_counts()



sns.countplot(data=train_df, x='Sentiment', palette='coolwarm')
plt.title('Sentiment distribution')

train_df.isnull().sum()

train_df = train_df.dropna()

train_df.shape

#preprocessing

def clean_text(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)         # remove links
    text = re.sub(r"@\w+", "", text)                   # remove mentions
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)        # remove punctuation
    text = re.sub(r"\s+", " ", text).strip()
    return text

train_df["clean"] = train_df["Text"].apply(clean_text)
valid_df["clean"] = valid_df["Text"].apply(clean_text)

train_df

y_train = train_df["Sentiment"]
y_valid = valid_df["Sentiment"]

tfidf = TfidfVectorizer(
    ngram_range=(1,2),
    min_df=2,
    max_features=40000
)

models = {
    "naive_bayes": MultinomialNB(),
    "logistic_regression": LogisticRegression(max_iter=2000),
    "random_forest": RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        n_jobs=-1
    )
}

trained_models = {}

for name, model in models.items():
    print(f"\n\n===== Training {name.upper()} =====\n")

    pipe = Pipeline([
        ("tfidf", tfidf),
        ("clf", model)
    ])

    pipe.fit(train_df["clean"], y_train)
    preds = pipe.predict(valid_df["clean"])

    print("Accuracy:", accuracy_score(y_valid, preds))
    print(classification_report(y_valid, preds))

    trained_models[name] = pipe

    joblib.dump(pipe, f"{name}_sentiment_model.pkl")
    print(f"Model saved to: {name}_sentiment_model.pkl")

nb_model = joblib.load("naive_bayes_sentiment_model.pkl")
lr_model = joblib.load("logistic_regression_sentiment_model.pkl")
rf_model = joblib.load("random_forest_sentiment_model.pkl")

i = 15
text = valid_df["clean"].iloc[i]
true_label = valid_df["Sentiment"].iloc[i]

print("Tweet:", text)
print("True:", true_label)

print("NB Prediction:", nb_model.predict([text])[0])
print("LR Prediction:", lr_model.predict([text])[0])
print("RF Prediction:", rf_model.predict([text])[0])

pip install streamlit pyngrok





















